export const SCROLL_RANGES = {
  ICON_CARD_SCALE: [0, 1],
  COLOR_LOGO_CARDS_SCALE: [0.3, 1],
  COLOR_LOGO_CARDS_TRANSLATE: [0.2, 1],
  VOICE_IMAGERY_CARDS_SCALE: [0.4, 1],
  CORNER_CARDS_SCALE: [0.8, 1],
  ICON_CARD_LINE_SCALE: [0, 1],
};

export const TRANSFORM_VALUES = {
  ICON_CARD_SCALE: [8.57, 1],
  COLOR_LOGO_CARDS_SCALE: [1.5, 1],
  VOICE_IMAGERY_CARDS_SCALE: [1.7, 1],
  CORNER_CARDS_SCALE: [1.7, 1],
  TRANSLATE_DISTANCE_NEGATIVE: [-1100, 0],
  TRANSLATE_DISTANCE_POSITIVE: [1100, 0],
  VOICE_TONE_CARD_TRANSLATE_Y: [-800, 0],
  IMAGERY_CARD_TRANSLATE_Y: [800, 0],
  CORNER_CARD_TRANSLATE_Y_UP: [-1100, 0],
  CORNER_CARD_TRANSLATE_Y_DOWN: [1100, 0],
  ICON_CARD_LINE_SCALE: [1 / 30, 1/5],
}; 